minor ui changes
LibertyDSNP/multiformat-inspector pull request #2
Opened 2024-08-13 22:03 UTC by aramikm

# Description
- removed the button and after every change it should try to decode
- Some more UI changes

# UI changes
![Screenshot 2024-08-13 at 3 03 12 PM](https://github.com/user-attachments/assets/e0133539-bce8-43fa-a362-70a32a20fd67)

2024-08-14 12:47 UTC, wilwade requested changes
One style suggestion and a need to run `npm run format` (No CI enforcement at this time for anything)

2024-08-14 12:47 UTC, wilwade commented on src/routes/+page.svelte
> +	}
Two small adjustments suggested to expand the padding some:
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/676e06cb-f659-4fb3-88ba-2f3c4a291401">


```suggestion
	table {
		width: 100%;
	}

	table, th, td {
		border: 1px solid black;
		border-collapse: collapse;
		padding: 5px;
	}
```

2024-08-14 20:23 UTC, wesbiggs approved these changes
Works for me

2024-08-15 12:35 UTC, wilwade approved these changes
🚢

2024-08-15 16:38 UTC, merged